- name: play level variables
  hosts: localhost
  connection: local
  vars:
    url: play.example.com
       - tasks
      - name: print url
       ansible.builtin.debug:
          msg: url - {{ url }}